spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meatshop_manager}
server.port=8081
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:meatshop-manager-secret-key-must-be-at-least-256-bits-long-for-hs256}
jwt.expiration=${JWT_EXPIRATION:86400000}